Module6 task3
htmlacademy-nodejs/1911649-typoteka-3 pull request #19
Opened 2022-05-13 07:15 UTC by AlexeyKonstantinov78

2022-05-13 21:00 UTC, html-malex requested changes
Если есть вопросы/замечания к комментариям - можешь написать мне в телеграм `@alexeymarunin`, обсудим :) 
PS это не будет считаться как консультация

2022-05-16 08:12 UTC, AlexeyKonstantinov78 commented on src/express/routes/main-routes.js
> +  const limit = OFFERS_PER_PAGE;
вынес только константу

2022-05-16 10:41 UTC, AlexeyKonstantinov78 commented on src/service/api/articles.e2e.test.js
> +  await initDB(mockDB, {categories: mockCategories, articles: mockData});
попробую собрать

2022-05-19 07:47 UTC, AlexeyKonstantinov78 commented on src/service/api/articles.e2e.test.js
> +  await initDB(mockDB, {categories: mockCategories, articles: mockData});
сервер тестовый вызывается  https://github.com/htmlacademy-nodejs/1911649-typoteka-3/pull/19/commits/8d6fc49d89d5064015cb7d169fa08abcea66307c

2022-05-20 09:12 UTC, AlexeyKonstantinov78 commented on src/express/routes/main-routes.js
> +  const limit = OFFERS_PER_PAGE;
Или всю переменную вынести, точнее тут убрать?

2022-05-20 09:56 UTC, AlexeyKonstantinov78 commented on src/service/api/articles.e2e.test.js
>    beforeAll(async () => {
переправил https://github.com/htmlacademy-nodejs/1911649-typoteka-3/pull/19/commits/68bdddeec87f31e4d2a0ebd1645bd0acb7e58fee

2022-05-20 12:15 UTC, html-malex requested changes

2022-05-20 12:18 UTC, AlexeyKonstantinov78 commented on src/service/api/articles.e2e.test.js
> +      `buy_and_sel_test`, DB_USER, DB_PASSWORD, {
https://github.com/htmlacademy-nodejs/1911649-typoteka-3/pull/19#discussion_r877472800 тогда и его можно будит вобще вызывать только отудова

2022-05-20 13:39 UTC, AlexeyKonstantinov78 commented on src/service/api/articles.e2e.test.js
> +      `buy_and_sel_test`, DB_USER, DB_PASSWORD, {
https://github.com/htmlacademy-nodejs/1911649-typoteka-3/pull/19#discussion_r877472800 вынес https://github.com/htmlacademy-nodejs/1911649-typoteka-3/pull/19/commits/27ffca51fc53d99e28de49e71007ac65d320f355

2022-05-20 13:44 UTC, AlexeyKonstantinov78 commented on src/service/api/articles.e2e.test.js
> +      `buy_and_sel_test`, DB_USER, DB_PASSWORD, {
https://github.com/htmlacademy-nodejs/1911649-typoteka-3/pull/19#discussion_r877477960 если я правильно понял мысль вынести в await initDB(mockDB, {categories: mockCategories, articles: mockData}); то тут будит нагромождение и не читаемо.

2022-05-20 13:56 UTC, AlexeyKonstantinov78 commented on src/service/api/articles.e2e.test.js
> +      `buy_and_sel_test`, DB_USER, DB_PASSWORD, {
https://github.com/htmlacademy-nodejs/1911649-typoteka-3/pull/19#discussion_r877477960 или так https://github.com/htmlacademy-nodejs/1911649-typoteka-3/pull/19/commits/7d73d34afc04f0e4682d62a68f2918598a75acce

2022-05-20 19:16 UTC, html-malex approved these changes

2022-05-20 19:16 UTC, merged